Attribute VB_Name = "Module3"
Option Explicit

'************************************************************
'************************************************************
'***                                                      ***
'***    Code Generated By: MDB Code Wizard ver. 1.0.6     ***
'***                   john@farrow.org                    ***
'***                                                      ***
'************************************************************
'************************************************************

'***NOTICE:***
'IN ORDER FOR THIS CODE TO WORK PROPERLY YOU MUST PROVIDE
'REFERENCE TO 'Microsoft DAO 2.5/3.51 Compatibility Library
Private DB As Database

Public Function Create_DatabaseBackup(strDBPath As String) As Boolean
'************************************************************
' Purpose: Creates a Microsoft Access Database with its
'          Tables, Indexes, Queries and Relationships.
'
' Inputs:
'   strDBPath:   path of the database to be created.
'
' Returns: True/False value indicating if the creation
'          process was successful.
'
' Database Details:
'   DB Path: 'C:\POS SALIM\Backup\TempDB97.mdb'
'   DB File DateStamp: 7/17/04 9:26:00 AM
'************************************************************

    Dim TblDef As TableDef
    Dim QryDef As QueryDef

    On Error GoTo ERR_ROUTINE

    Set DB = DBEngine(0).CreateDatabase(strDBPath, dbLangGeneral, dbEncrypt + dbVersion30)

    'CREATE TABLE DEFINITIONS
    '=============================
    Create_TblDef_MSales
    Create_TblDef_MSalesD

    'CREATE QUERY DEFINITIONS
    '=============================

    'CREATE RELATIONSHIPS
    '=============================
    Create_DatabaseBackup = True
DB.Close
Set DB = Nothing
Exit Function

ERR_ROUTINE:
    Create_DatabaseBackup = False
    MsgBox Err.Number & vbCrLf & vbCrLf & Err.Description, vbCritical
End Function

Private Sub Create_TblDef_MSales()
    Dim TblDef As TableDef
    Dim Fld As Field
    Dim Idx As Index

    'CREATE TABLE: MSales
    '=============================
    Set TblDef = DB.CreateTableDef("MSales")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: NoID
        '=============================
        Set Fld = TblDef.CreateField("NoID", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 0
            .Required = True
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Kode
        '=============================
        Set Fld = TblDef.CreateField("Kode", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = "0"
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Tanggal
        '=============================
        Set Fld = TblDef.CreateField("Tanggal", 8, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = "Date()"
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: TotalPajak
        '=============================
        Set Fld = TblDef.CreateField("TotalPajak", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: TotalDiscount
        '=============================
        Set Fld = TblDef.CreateField("TotalDiscount", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: SubTotal
        '=============================
        Set Fld = TblDef.CreateField("SubTotal", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: DiscNota
        '=============================
        Set Fld = TblDef.CreateField("DiscNota", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: HargaTotal
        '=============================
        Set Fld = TblDef.CreateField("HargaTotal", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDPayment
        '=============================
        Set Fld = TblDef.CreateField("IDPayment", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 8
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: UangMuka
        '=============================
        Set Fld = TblDef.CreateField("UangMuka", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDUser
        '=============================
        Set Fld = TblDef.CreateField("IDUser", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
    'CREATE FIELD: IDBank
        '=============================
        Set Fld = TblDef.CreateField("IDBank", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         'CREATE FIELD: KodeMember
        '=============================
        Set Fld = TblDef.CreateField("KodeMember", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = "0"
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld
        
  'CREATE FIELD: IDCustomer
        '=============================
        Set Fld = TblDef.CreateField("IDCustomer", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         'CREATE FIELD: IDVoucher
        '=============================
        Set Fld = TblDef.CreateField("IDVoucher", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        'CREATE FIELD: IsSend
        '=============================
        Set Fld = TblDef.CreateField("IsSend", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Bank
        '=============================
        Set Fld = TblDef.CreateField("Bank", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Bank
        '=============================
        Set Fld = TblDef.CreateField("Voucher", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        'CREATE FIELD: ISPending
        '=============================
        Set Fld = TblDef.CreateField("ISPending", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Shift
        '=============================
        Set Fld = TblDef.CreateField("Shift", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 14
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         'CREATE FIELD: IsUpload
        '=============================
        Set Fld = TblDef.CreateField("IsUpload", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        
         'CREATE FIELD: JumDiscInternRp
        '=============================
        Set Fld = TblDef.CreateField("JumDiscInternRp", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

  'CREATE FIELD: JumDiscInternRp
        '=============================
        Set Fld = TblDef.CreateField("DiscIntern", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
          'CREATE FIELD: IDMember
        '=============================
        Set Fld = TblDef.CreateField("IDMember", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        
           'CREATE FIELD: BarangKSB
        '=============================
        Set Fld = TblDef.CreateField("BarangKSB", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         
           'CREATE FIELD: SisaKSB
        '=============================
        Set Fld = TblDef.CreateField("SisaKSB", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 8
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         'CREATE FIELD: DiscNota
        '=============================
        Set Fld = TblDef.CreateField("Pembulatan", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
'MSales.IDMember , MSales.BarangKSB, MSales.SisaKSB

        'CREATE INDEX: IDPayment
        '=============================
        Set Idx = TblDef.CreateIndex("IDPayment")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IDPayment")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: IDUse
        '=============================
        Set Idx = TblDef.CreateIndex("IDUse")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IDUser")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("NoID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub

Private Sub Create_TblDef_MSalesD()
    Dim TblDef As TableDef
    Dim Fld As Field
    Dim Idx As Index

    'CREATE TABLE: MSalesD
    '=============================
    Set TblDef = DB.CreateTableDef("MSalesD")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: NoID
        '=============================
        Set Fld = TblDef.CreateField("NoID", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 0
            .Required = True
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDSales
        '=============================
        Set Fld = TblDef.CreateField("IDSales", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDInventor
        '=============================
        Set Fld = TblDef.CreateField("IDInventor", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Qty
        '=============================
        Set Fld = TblDef.CreateField("Qty", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Harga
        '=============================
        Set Fld = TblDef.CreateField("Harga", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: KodeInv
        '=============================
        Set Fld = TblDef.CreateField("KodeInv", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: NamaInv
        '=============================
        Set Fld = TblDef.CreateField("NamaInv", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Satuan
        '=============================
        Set Fld = TblDef.CreateField("Satuan", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Barcode
        '=============================
        Set Fld = TblDef.CreateField("Barcode", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 8
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDSatuan
        '=============================
        Set Fld = TblDef.CreateField("IDSatuan", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Konversi
        '=============================
        Set Fld = TblDef.CreateField("Konversi", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IsSend
        '=============================
        Set Fld = TblDef.CreateField("IsSend", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Transaksi
        '=============================
        Set Fld = TblDef.CreateField("Transaksi", 10, 3)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: HargaPokok
        '=============================
        Set Fld = TblDef.CreateField("HargaPokok", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        'CREATE FIELD: HargaBruto
        '=============================
        Set Fld = TblDef.CreateField("HargaBruto", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        'CREATE FIELD: DiscRp
        '=============================
        Set Fld = TblDef.CreateField("DiscRp", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
         'CREATE FIELD: DiscProsen
        '=============================
        Set Fld = TblDef.CreateField("DiscProsen", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

         'CREATE FIELD: DiscProsen1
        '=============================
        Set Fld = TblDef.CreateField("DiscProsen1", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        
        
         'CREATE FIELD: DiscProsen2
        '=============================
        Set Fld = TblDef.CreateField("DiscProsen2", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        

         'CREATE FIELD: DiscProsen3
        '=============================
        Set Fld = TblDef.CreateField("DiscProsen3", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        

        'CREATE FIELD: Jumlah
        '=============================
        Set Fld = TblDef.CreateField("Jumlah", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 14
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
 'CREATE FIELD: DiscRp
        '=============================
        Set Fld = TblDef.CreateField("DiscInternRp", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 15
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
 

'CREATE FIELD: Disc1
        '=============================
        Set Fld = TblDef.CreateField("Disc1", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 16
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
               


'CREATE FIELD: Disc2
        '=============================
        Set Fld = TblDef.CreateField("Disc2", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 17
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
               
'CREATE FIELD: Disc3
        '=============================
        Set Fld = TblDef.CreateField("Disc3", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 18
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
         

               
'CREATE FIELD: HargaMin
        '=============================
        Set Fld = TblDef.CreateField("HargaMin", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 19
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld


'CREATE FIELD: HargaDisc
        '=============================
        Set Fld = TblDef.CreateField("HargaDisc", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 20
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

'CREATE FIELD: HargaD
        '=============================
        Set Fld = TblDef.CreateField("HargaD", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 21
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld





             

         'CREATE FIELD: DiscProsen
        '=============================
        Set Fld = TblDef.CreateField("DiscInternProsen", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
           'CREATE FIELD: IsSend
        '=============================
        Set Fld = TblDef.CreateField("IsMember", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 14
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        'CREATE INDEX: Barcode
        '=============================
        Set Idx = TblDef.CreateIndex("Barcode")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("Barcode")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: IDSatuan
        '=============================
        Set Idx = TblDef.CreateIndex("IDSatuan")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IDSatuan")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("NoID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub


