Attribute VB_Name = "Module4"
Option Explicit

'************************************************************
'************************************************************
'***                                                      ***
'***    Code Generated By: MDB Code Wizard ver. 1.0.6     ***
'***                   john@farrow.org                    ***
'***                                                      ***
'************************************************************
'************************************************************

'***NOTICE:***
'IN ORDER FOR THIS CODE TO WORK PROPERLY YOU MUST PROVIDE
'REFERENCE TO 'Microsoft DAO 2.5/3.51 Compatibility Library
Private DB As Database

Public Function Create_DatabaseResetDua(strDBPath As String) As Boolean
'************************************************************
' Purpose: Creates a Microsoft Access Database with its
'          Tables, Indexes, Queries and Relationships.
'
' Inputs:
'   strDBPath:   path of the database to be created.
'
' Returns: True/False value indicating if the creation
'          process was successful.
'
' Database Details:
'   DB Path: 'C:\POS SALIM\97\TempDB"& format(now,"_yyyyMM") &".mdb'
'   DB File DateStamp: 7/23/04 9:03:32 AM
'************************************************************

    Dim TblDef As TableDef
    Dim QryDef As QueryDef

    On Error GoTo ERR_ROUTINE

    Set DB = DBEngine(0).CreateDatabase(strDBPath, dbLangGeneral, 0)

    'CREATE TABLE DEFINITIONS
    '=============================
    Create_TblDef_MSales
    Create_TblDef_MSalesD

    'CREATE QUERY DEFINITIONS
    '=============================

    'CREATE RELATIONSHIPS
    '=============================
    Create_DatabaseResetDua = True
DB.Close
Set DB = Nothing
Exit Function

ERR_ROUTINE:
    Create_DatabaseResetDua = False
    MsgBox Err.Number & vbCrLf & vbCrLf & Err.Description, vbCritical
End Function

Private Sub Create_TblDef_MSales()
    Dim TblDef As TableDef
    Dim Fld As Field
    Dim Idx As Index

    'CREATE TABLE: MSales
    '=============================
    Set TblDef = DB.CreateTableDef("MSales")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: NoID
        '=============================
        Set Fld = TblDef.CreateField("NoID", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 0
            .Required = True
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Kode
        '=============================
        Set Fld = TblDef.CreateField("Kode", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = "0"
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Tanggal
        '=============================
        Set Fld = TblDef.CreateField("Tanggal", 8, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = "Now()"
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: SubTotal
        '=============================
        Set Fld = TblDef.CreateField("SubTotal", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: DiscNota
        '=============================
        Set Fld = TblDef.CreateField("DiscNota", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: HargaTotal
        '=============================
        Set Fld = TblDef.CreateField("HargaTotal", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Tunai
        '=============================
        Set Fld = TblDef.CreateField("Tunai", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Bank
        '=============================
        Set Fld = TblDef.CreateField("Bank", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
      
      'CREATE FIELD: Voucher
        '=============================
        Set Fld = TblDef.CreateField("Voucher", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        'CREATE FIELD: JumlahNota
        '=============================
'        Set Fld = TblDef.CreateField("JumlahNota", 4, 4)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 8
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld

        'CREATE FIELD: IDUser
        '=============================
        Set Fld = TblDef.CreateField("IDUser", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDUser
        '=============================
        Set Fld = TblDef.CreateField("IDBank", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld
        'CREATE FIELD: NamaUser
        '=============================
        Set Fld = TblDef.CreateField("NamaUser", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = True
        End With
        .Fields.Append Fld

        'CREATE FIELD: IsSend
        '=============================
        Set Fld = TblDef.CreateField("IsSend", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Shift
        '=============================
        Set Fld = TblDef.CreateField("Shift", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IdPengawas
        '=============================
        Set Fld = TblDef.CreateField("IdPengawas", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: NamaPengawas
        '=============================
        Set Fld = TblDef.CreateField("NamaPengawas", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 14
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = True
        End With
        .Fields.Append Fld

'        'CREATE FIELD: PajakPersen
'        '=============================
'        Set Fld = TblDef.CreateField("PajakPersen", 6, 4)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 15
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld

'        'CREATE FIELD: TunaiPajak
'        '=============================
'        Set Fld = TblDef.CreateField("TunaiPajak", 5, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 16
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld
'        'CREATE FIELD: NotaMax
'        '=============================
'        Set Fld = TblDef.CreateField("NotaMax", 5, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 3
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld
'
'                'CREATE FIELD: NotaMin
'        '=============================
'        Set Fld = TblDef.CreateField("NotaMin", 5, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 3
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld
        
        'CREATE INDEX: IdPengawas
        '=============================
        Set Idx = TblDef.CreateIndex("IdPengawas")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IdPengawas")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: IDUse
        '=============================
        Set Idx = TblDef.CreateIndex("IDUse")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IDUser")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("NoID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub

Private Sub Create_TblDef_MSalesD()
    Dim TblDef As TableDef
    Dim Fld As Field
    Dim Idx As Index

    'CREATE TABLE: MSalesD
    '=============================
    Set TblDef = DB.CreateTableDef("MSalesD")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: NoID
        '=============================
        Set Fld = TblDef.CreateField("NoID", 4, 4)
        With Fld
            .Attributes = 17
            .DefaultValue = ""
            .OrdinalPosition = 0
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDSales
        '=============================
        Set Fld = TblDef.CreateField("IDSales", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDInventor
        '=============================
        Set Fld = TblDef.CreateField("IDInventor", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Qty
        '=============================
        Set Fld = TblDef.CreateField("Qty", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: HargaSat
        '=============================
        Set Fld = TblDef.CreateField("HargaSat", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Harga
        '=============================
        Set Fld = TblDef.CreateField("Harga", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: KodeInv
        '=============================
        Set Fld = TblDef.CreateField("KodeInv", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: NamaInv
        '=============================
        Set Fld = TblDef.CreateField("NamaInv", 10, 50)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Satuan
        '=============================
        Set Fld = TblDef.CreateField("Satuan", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 8
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: Barcode
        '=============================
        Set Fld = TblDef.CreateField("Barcode", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: IDSatuan
        '=============================
        Set Fld = TblDef.CreateField("IDSatuan", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Konversi
        '=============================
        Set Fld = TblDef.CreateField("Konversi", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: IsSend
        '=============================
        Set Fld = TblDef.CreateField("IsSend", 1, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

'        'CREATE FIELD: Transaksi
'        '=============================
'        Set Fld = TblDef.CreateField("Transaksi", 10, 3)
'        With Fld
'            .Attributes = 2
'            .DefaultValue = ""
'            .OrdinalPosition = 13
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'            .AllowZeroLength = False
'        End With
'        .Fields.Append Fld

        'CREATE FIELD: HargaPokok
        '=============================
        Set Fld = TblDef.CreateField("HargaPokok", 5, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 14
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

'        'CREATE FIELD: QtyPjk
'        '=============================
'        Set Fld = TblDef.CreateField("QtyPjk", 7, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 15
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld
'
'        'CREATE FIELD: HargaSatP
'        '=============================
'        Set Fld = TblDef.CreateField("HargaSatP", 5, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 16
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld
'
'        'CREATE FIELD: HargaP
'        '=============================
'        Set Fld = TblDef.CreateField("HargaP", 5, 8)
'        With Fld
'            .Attributes = 1
'            .DefaultValue = 0
'            .OrdinalPosition = 17
'            .Required = False
'            .ValidationRule = ""
'            .ValidationText = ""
'        End With
'        .Fields.Append Fld

        'CREATE INDEX: Barcode
        '=============================
        Set Idx = TblDef.CreateIndex("Barcode")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("Barcode")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: IDSatuan
        '=============================
        Set Idx = TblDef.CreateIndex("IDSatuan")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("IDSatuan")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("NoID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub


